import Head from 'next/head';
import Image from 'next/image';
import Question from '../features/questions/Question';
export default function Home() {
	return (
		<div className="">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<h1 className="bg-red-500">Hello world!</h1>
			<Question />
		</div>
	);
}
